Implement 1.11-accounts
Azure/sap-hana pull request #1130
Opened 2021-04-30 02:06 UTC by rtamalin

Implement a role that can be used to create admin account, and
associated groups, with matching /etc/sudoers.d/<username> files.

The role supports both adding and removing admin users and groups,
as well as allowing account settings to be associated with a given
playbook tier, and enabled/disabled via the associated attribute.

The details of the admin groups and accounts to be created are specified
in the top level vars/admin-accounts.yml file. Currently this file holds
plain text passwords and static uid and gid definitions; this needs to
change to creating/retrieving passwords from a secure source such as a
keyvault, and allow for dynamic uid & gid assignments which are tracked
in a persistent fashion in a keyvault.

Currently just two "flavours" of sudoers roles are defined:
  * admin_no_password:
    all commands permitted without need to enter a password.
  * admin_password_required:
    all commands permitted but password validation required.

Additional flavours can be added by adding new templates with a name
in the format 'sudoers_<role_name>.j2'. Optionally a vars file with
the same name can be created, which will be dynamically loaded if
found, that can hold any useful fact definitions that may aid in
processing the matching template file.

## Problem
<Please describe what problem this PR is trying to resolve>

## Solution
<Please elaborate the solution for the problem>

## Tests
<Please provide steps to test the PR>

## Notes
<Additional comments for the PR>

2021-04-30 02:11 UTC, rtamalin commented
@KimForss @mkdeegan I'm tested this creating and removing the reference example user/group, so the "plumbing" is working correct. The next step would be to add the appropriate user settings to the `vars/admin-accounts.yml` for any reference admin user we want to create in our test deployments for the `os` playbook tier and similarly add initial details for any SAP accounts we want to manage for the other playbook tiers... Hopefully it should just be a matter of re-including this role as the "2.3 create SAP users" step, at least for the first pass...

2021-04-30 14:59 UTC, mkdeegan requested changes

2021-04-30 14:59 UTC, mkdeegan commented on deploy/ansible/roles-os/1.0-sudoers/defaults/setup_user_sudoers.yml
> +sudoers_path:  /etc/sudoers.d
as discussed, this is unit of work should not be cross role, and is better performed from 1.11-accounts.
Please relocate.

2021-04-30 14:59 UTC, mkdeegan commented on deploy/ansible/roles-os/1.0-sudoers/tasks/setup_user_sudoers.yml
> +    -           sudoers_state == "absent"
as discussed, this is unit of work should not be cross role, and is better performed from 1.11-accounts.
Please relocate.

2021-04-30 14:59 UTC, mkdeegan commented on deploy/ansible/roles-os/1.0-sudoers/templates/sudoers_admin_no_password.j2
> +{{ sudoers_user }} ALL=(ALL) NOPASSWD:ALL
as discussed, this is unit of work should not be cross role, and is better performed from 1.11-accounts.
Please relocate.

2021-04-30 14:59 UTC, mkdeegan commented on deploy/ansible/roles-os/1.0-sudoers/templates/sudoers_admin_password_required.j2
> +{{ sudoers_user }} ALL=(ALL) PASSWD:ALL
as discussed, this is unit of work should not be cross role, and is better performed from 1.11-accounts.
Please relocate.

2021-04-30 14:59 UTC, mkdeegan commented on deploy/ansible/roles-os/1.0-sudoers/vars/sudoers_default.yml
> +# -------------------------------------+---------------------------------------8
as discussed, this is unit of work should not be cross role, and is better performed from 1.11-accounts.
Please relocate.

2021-04-30 22:18 UTC, rtamalin commented on deploy/ansible/roles-os/1.0-sudoers/defaults/setup_user_sudoers.yml
> +sudoers_path:  /etc/sudoers.d
Done

2021-04-30 22:18 UTC, rtamalin commented on deploy/ansible/roles-os/1.0-sudoers/tasks/setup_user_sudoers.yml
> +    -           sudoers_state == "absent"
Done

2021-04-30 22:19 UTC, rtamalin commented on deploy/ansible/roles-os/1.0-sudoers/templates/sudoers_admin_no_password.j2
> +{{ sudoers_user }} ALL=(ALL) NOPASSWD:ALL
Done

2021-04-30 22:19 UTC, rtamalin commented on deploy/ansible/roles-os/1.0-sudoers/templates/sudoers_admin_password_required.j2
> +{{ sudoers_user }} ALL=(ALL) PASSWD:ALL
Done

2021-04-30 22:19 UTC, rtamalin commented on deploy/ansible/roles-os/1.0-sudoers/vars/sudoers_default.yml
> +# -------------------------------------+---------------------------------------8
Done

2021-04-30 22:21 UTC, rtamalin commented
@mkdeegan As requested I've moved the bits I added to the 1.0-sudoers role into the 1.11-accounts role... Wasn't able to entirely eliminate the use of includes though. ;-)

2021-05-16 17:49 UTC, merged

2021-05-16 17:49 UTC, KimForss commented
Let's merge this and revisit if needed

2021-05-16 17:50 UTC, KimForss reviewed
Looks good to me