Alfa
Azure/sap-hana pull request #1151
Opened 2021-05-26 10:32 UTC by PankajMeshramCSA

## Problem
Added the Task for Services state  

## Solution
This Task will let the customers specify customer list of services which they want to stop, start, enable or disable 

## Tests
In the vars, please refer to os-services.yaml where one can specify list of services. You would see few services which I have tested against red hat8 OS. 

## Notes
<Additional comments for the PR>

2021-05-26 14:28 UTC, rtamalin requested changes
You also are missing a change in the `playbook_01_os_base_config.yaml` so that this role will actually be called...

2021-05-26 14:28 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/tasks/main.yaml
> +- name:             "1.16 - Disable Services : {{ distro_name }}"
So I would probably move the disable to happen before the stop... It is a subtle thing, but usually a good idea to disable the service before stopping it, just in case there is any sort of service dependency chain that can trigger it to be automatically restarted again if not marked as disabled...

The usual logic I apply is that I do a start before an enable, to ensure that the service start is working correctly before enabling it to auto start. And conversely when undoing those I usually do them in reverse order, i.e. disable first then stop...

2021-05-26 14:28 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: '',  node_tier: 'all',    state: 'started' }
You probably should either fill out entries for RHEL 7, or comment these lines out, as I think an empty service string is being interpretted as "all services" from what your verbose output showed yesterday.

Since this is the same line repeated 3 times, probably for now remove the duplicates, and comment out the remaining line.

2021-05-26 14:28 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: 'nfs-server',   node_tier: 'all',     state: 'enabled' }
Do we want all nodes to be enabled as NFS servers? I believe our current deployment strategy has one node act as an NFS server, while the other nodes that need to access the shared data only need to be NFS clients and not full servers. So you probably need to specify the appropriate node_tier value here...

2021-05-26 14:28 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: '',  node_tier: 'all',     state: 'started' }
The same as for the RHEL 7 case, probably best to not have duplicate lines, and just leave a single line here, commented out, for reference, until we actually have SLE 12 specific settings.

2021-05-26 14:28 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: '',  node_tier: 'all',     state: 'started' }
The same as for the RHEL 7 case, probably best to not have duplicate lines, and just leave a single line here, commented out, for reference, until we actually have SLE 15 specific settings.

2021-05-26 20:06 UTC, PankajMeshramCSA commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: '',  node_tier: 'all',    state: 'started' }
done as requested.

2021-05-26 20:09 UTC, PankajMeshramCSA commented
Hi @Fergal Mc ***@***.***>,

I have resolved all the requests and pushed the changes. Could you please check and review now ?

Pankaj Meshram
Cloud Solution Architect- SAP on Azure
United Kingdom
One Commercial Partner
Phone: +44 (118) 9095515
Mobile: +44 7973 667128
***@***.******@***.***>

***@***.***D75273.56402500]

***@***.******@***.***D75273.56402500]

Planned Leave - 31st May to 4th June




From: Fergal Mc Carthy ***@***.***>
Sent: 26 May 2021 15:29
To: Azure/sap-hana ***@***.***>
Cc: Pankaj Meshram ***@***.***>; Author ***@***.***>
Subject: Re: [Azure/sap-hana] Alfa (#1151)


@rtamalin requested changes on this pull request.

You also are missing a change in the playbook_01_os_base_config.yaml so that this role will actually be called...

________________________________

In deploy/ansible/roles-os/1.16-services/tasks/main.yaml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-hana%2Fpull%2F1151%23discussion_r639775513&data=04%7C01%7Cpankaj.meshram%40microsoft.com%7C05ae6d788d9f490f75f208d920529599%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637576361352947976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s0sdN2h5XRF1oE745SJPWhWkko6EzRWw4Kkigs%2FZ5jo%3D&reserved=0>:

> +    enabled:         yes

+  loop:             "{{ services_to_process |

+                      selectattr('state', 'equalto', 'enabled') |

+                      map(attribute='service') |

+                      list }}"

+

+- name:             "1.16 - Stop Services : {{ distro_name }}"

+  service:

+    name:           "{{ item }}"

+    state:          stopped

+  loop:           "{{ services_to_process |

+                      selectattr('state', 'equalto', 'stopped') |

+                      map(attribute='service') |

+                      list }}"

+

+- name:             "1.16 - Disable Services : {{ distro_name }}"

So I would probably move the disable to happen before the stop... It is a subtle thing, but usually a good idea to disable the service before stopping it, just in case there is any sort of service dependency chain that can trigger it to be automatically restarted again if not marked as disabled...

The usual logic I apply is that I do a start before an enable, to ensure that the service start is working correctly before enabling it to auto start. And conversely when undoing those I usually do them in reverse order, i.e. disable first then stop...

________________________________

In deploy/ansible/roles-os/1.16-services/vars/os-services.yaml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-hana%2Fpull%2F1151%23discussion_r639775631&data=04%7C01%7Cpankaj.meshram%40microsoft.com%7C05ae6d788d9f490f75f208d920529599%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637576361352957976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G0%2Bk7PS4oX7zJtJJwHjvHcvU4zMtFzmMGI7a67CUUh8%3D&reserved=0>:

> +

+# For each supported 'distro_id' we want a list of dictionary entries that

+# specify the associated tier (or 'all' to always match), the service name,

+# and whether we want the service to be enabled and started or disabled

+# and stopped. See the definition of 'distro_id' to determine what to use when

+# creating an entry for a new distribution.

+# In this list one can specify the custom list of services to be enabled,disabled

+# OR started, stopped

+

+#Example - Add a line specifying the service, SAP node teir & state

+# redhat8:

+#      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' }

+

+services:

+    redhat7:

+      - { tier: 'os', service: '',  node_tier: 'all',    state: 'started' }

You probably should either fill out entries for RHEL 7, or comment these lines out, as I think an empty service string is being interpretted as "all services" from what your verbose output showed yesterday.

Since this is the same line repeated 3 times, probably for now remove the duplicates, and comment out the remaining line.

________________________________

In deploy/ansible/roles-os/1.16-services/vars/os-services.yaml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-hana%2Fpull%2F1151%23discussion_r639777964&data=04%7C01%7Cpankaj.meshram%40microsoft.com%7C05ae6d788d9f490f75f208d920529599%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637576361352967966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dIAloeTs%2BYVS8UjdOQNPY3jR35%2F9ZEKmX3gBIjOpFhY%3D&reserved=0>:

> +#Example - Add a line specifying the service, SAP node teir & state

+# redhat8:

+#      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' }

+

+services:

+    redhat7:

+      - { tier: 'os', service: '',  node_tier: 'all',    state: 'started' }

+      - { tier: 'os', service: '',  node_tier: 'all',   state: 'started' }

+      - { tier: 'os', service: '',  node_tier: 'all',   state: 'started' }

+

+

+    redhat8:

+      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' }

+      - { tier: 'os', service: 'multipathd',   node_tier: 'all',     state: 'stopped' }

+      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'disabled' }

+      - { tier: 'os', service: 'nfs-server',   node_tier: 'all',     state: 'enabled' }

Do we want all nodes to be enabled as NFS servers? I believe our current deployment strategy has one node act as an NFS server, while the other nodes that need to access the shared data only need to be NFS clients and not full servers. So you probably need to specify the appropriate node_tier value here...

________________________________

In deploy/ansible/roles-os/1.16-services/vars/os-services.yaml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-hana%2Fpull%2F1151%23discussion_r639779386&data=04%7C01%7Cpankaj.meshram%40microsoft.com%7C05ae6d788d9f490f75f208d920529599%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637576361352967966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pQ7%2FsxMTXkOMv1yF7F3ZQA2Gc%2BO7CN6i0iBZ7PN26kY%3D&reserved=0>:

> +    redhat7:

+      - { tier: 'os', service: '',  node_tier: 'all',    state: 'started' }

+      - { tier: 'os', service: '',  node_tier: 'all',   state: 'started' }

+      - { tier: 'os', service: '',  node_tier: 'all',   state: 'started' }

+

+

+    redhat8:

+      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' }

+      - { tier: 'os', service: 'multipathd',   node_tier: 'all',     state: 'stopped' }

+      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'disabled' }

+      - { tier: 'os', service: 'nfs-server',   node_tier: 'all',     state: 'enabled' }

+      - { tier: 'os', service: 'sbd',          node_tier: 'all',     state: 'enabled' }

+

+

+    suse12:

+      - { tier: 'os', service: '',  node_tier: 'all',     state: 'started' }

The same as for the RHEL 7 case, probably best to not have duplicate lines, and just leave a single line here, commented out, for reference, until we actually have SLE 12 specific settings.

________________________________

In deploy/ansible/roles-os/1.16-services/vars/os-services.yaml<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsap-hana%2Fpull%2F1151%23discussion_r639779711&data=04%7C01%7Cpankaj.meshram%40microsoft.com%7C05ae6d788d9f490f75f208d920529599%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637576361352977965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c4XHepurSh1tRLQMH%2BgfLewGaJJK4GIqZ3k0TvHTCZA%3D&reserved=0>:

> +    redhat8:

+      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'started' } [...]

2021-05-27 15:02 UTC, rtamalin commented
Looks good now @PankajMeshramCSA.

2021-06-04 10:19 UTC, KimForss commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'disabled' }
Why is auditd specified twice`?

2021-06-07 09:54 UTC, PankajMeshramCSA commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'disabled' }
I remember this point was raised where a service should be first disabled and stopped. I have added both the states now where a service for example "auditd" is started and enabled or a service for example "multipathd" is disabled and stopped. please review.

2021-06-07 21:03 UTC, rtamalin commented on deploy/ansible/roles-os/1.16-services/vars/os-services.yaml
> +      - { tier: 'os', service: 'auditd',       node_tier: 'all',     state: 'disabled' }
The point about disable then stopp is for the internal implementation, not the state represented in the table here.

If the target goal, specified in the table here, is to disable a service, then you implicitly need to also stop any running instances of it as well. But when doing so it is best to disable the service from starting before stopping any running instances, to ensure that nothing can trigger an automatic restart of the service when you stop it.

2021-06-08 15:25 UTC, merged