WebDispatcher installation on -web VMs
Azure/sap-hana pull request #1185
Opened 2021-06-16 12:05 UTC by msftrobiro

## Problem
Ansible playbook to install SAP Web Dispatcher on standalone web VMs

## Solution
New playbook, ini param file for SAP installation for Web Dispatcher

## Tests
<Please provide steps to test the PR>

## Notes
Two ToDos open to be addressed
- SAPWEBDISP.SAR needs to be part of BOM download, it is NOT part of S/4 Maintenance Planner operation and thus needs to be separately added.
- This PR only covers standalone WDisp, integrated (in ASCS) is NOT covered at the moment. Also not covered presently is ILB or AppGw in front of WebDispatcher VM(s), in Terraform

2021-06-16 15:47 UTC, mkdeegan requested changes

2021-06-16 15:47 UTC, mkdeegan commented on .vscode/settings.json
>  }
This file should not be getting committed to GitHub ... 
It should be ignored

2021-06-16 15:47 UTC, mkdeegan commented on deploy/ansible/playbook_05_04_sap_web_install.yaml
> +# |                 Playbook for SAP Application Server Install                |
Name is wrong... Not Application Server

2021-06-16 15:47 UTC, mkdeegan commented on deploy/ansible/playbook_05_04_sap_web_install.yaml
> +  serial:         1
Web Dispatchers don't need the serial parameter, I believe

2021-06-16 15:47 UTC, mkdeegan commented on deploy/ansible/roles-sap/5.4-web-install/tasks/main.yaml
> +#------------------</DEBUGGING>------------------
Review this code. The as written code follows a old process that will no longer work.
The other install roles have already been updated.

2021-06-17 13:53 UTC, msftrobiro commented on .vscode/settings.json
>  }
Thanks, corrected.

2021-06-17 13:54 UTC, msftrobiro commented on deploy/ansible/playbook_05_04_sap_web_install.yaml
> +# |                 Playbook for SAP Application Server Install                |
Thanks, corrected.

2021-06-17 13:56 UTC, msftrobiro commented on deploy/ansible/playbook_05_04_sap_web_install.yaml
> +  serial:         1
Unfortunately yes. We use a shared directory for sapinst_instdir. And without serial it clashes (and possibly other errors)
Could add hostname parameter to the installation directory but that should be then done for all installations, as each App servers also overwrites the installation dir since they use same path on nfs.

2021-06-17 13:56 UTC, msftrobiro commented on deploy/ansible/roles-sap/5.4-web-install/tasks/main.yaml
> +#------------------</DEBUGGING>------------------
As discussed, was working off the older code. Corrected and tested with new format.

2021-06-23 17:16 UTC, mkdeegan approved these changes

2021-06-23 17:16 UTC, merged